import { PlayerModel } from "../models/playerModel"

const database: PlayerModel[] = [
  {
    id: 1,
    name: "Lionel Messi",
    club: "Paris Saint-Germain",
    nationality: "Argentina",
    position: "Forward",
    statistics: {
      Overall: 93,
      Pace: 85,
      Shooting: 94,
      Passing: 91,
      Dribbling: 95,
      Defending: 38,
      Physical: 65,
    },
  },
  {
    id: 2,
    name: "Cristiano Ronaldo",
    club: "Al Nassr",
    nationality: "Portugal",
    position: "Forward",
    statistics: {
      Overall: 91,
      Pace: 87,
      Shooting: 93,
      Passing: 82,
      Dribbling: 88,
      Defending: 35,
      Physical: 78,
    },
  },
  {
    id: 3,
    name: "Kylian Mbappé",
    club: "Paris Saint-Germain",
    nationality: "France",
    position: "Forward",
    statistics: {
      Overall: 92,
      Pace: 97,
      Shooting: 89,
      Passing: 80,
      Dribbling: 92,
      Defending: 36,
      Physical: 76,
    },
  },
  {
    id: 4,
    name: "Kevin De Bruyne",
    club: "Manchester City",
    nationality: "Belgium",
    position: "Midfielder",
    statistics: {
      Overall: 91,
      Pace: 76,
      Shooting: 86,
      Passing: 94,
      Dribbling: 88,
      Defending: 64,
      Physical: 78,
    },
  },
  {
    id: 5,
    name: "Robert Lewandowski",
    club: "Barcelona",
    nationality: "Poland",
    position: "Forward",
    statistics: {
      Overall: 91,
      Pace: 78,
      Shooting: 93,
      Passing: 79,
      Dribbling: 85,
      Defending: 45,
      Physical: 82,
    },
  },
  {
    id: 6,
    name: "Erling Haaland",
    club: "Manchester City",
    nationality: "Norway",
    position: "Forward",
    statistics: {
      Overall: 89,
      Pace: 91,
      Shooting: 90,
      Passing: 72,
      Dribbling: 82,
      Defending: 42,
      Physical: 88,
    },
  },
  {
    id: 7,
    name: "Neymar Jr.",
    club: "Al Hilal",
    nationality: "Brazil",
    position: "Forward",
    statistics: {
      Overall: 90,
      Pace: 88,
      Shooting: 85,
      Passing: 87,
      Dribbling: 94,
      Defending: 38,
      Physical: 60,
    },
  },
  {
    id: 8,
    name: "Mohamed Salah",
    club: "Liverpool",
    nationality: "Egypt",
    position: "Forward",
    statistics: {
      Overall: 89,
      Pace: 93,
      Shooting: 86,
      Passing: 81,
      Dribbling: 90,
      Defending: 45,
      Physical: 74,
    },
  },
  {
    id: 9,
    name: "Virgil van Dijk",
    club: "Liverpool",
    nationality: "Netherlands",
    position: "Defender",
    statistics: {
      Overall: 90,
      Pace: 78,
      Shooting: 60,
      Passing: 71,
      Dribbling: 70,
      Defending: 91,
      Physical: 86,
    },
  },
  {
    id: 10,
    name: "Luka Modrić",
    club: "Real Madrid",
    nationality: "Croatia",
    position: "Midfielder",
    statistics: {
      Overall: 88,
      Pace: 74,
      Shooting: 76,
      Passing: 89,
      Dribbling: 88,
      Defending: 70,
      Physical: 66,
    },
  },
  {
    id: 11,
    name: "Thibaut Courtois",
    club: "Real Madrid",
    nationality: "Belgium",
    position: "Goalkeeper",
    statistics: {
      Overall: 90,
      Pace: 50,
      Shooting: 25,
      Passing: 58,
      Dribbling: 45,
      Defending: 16,
      Physical: 80,
    },
  },
  {
    id: 12,
    name: "Karim Benzema",
    club: "Al-Ittihad",
    nationality: "France",
    position: "Forward",
    statistics: {
      Overall: 89,
      Pace: 78,
      Shooting: 90,
      Passing: 83,
      Dribbling: 87,
      Defending: 40,
      Physical: 79,
    },
  },
  {
    id: 13,
    name: "Harry Kane",
    club: "Bayern Munich",
    nationality: "England",
    position: "Forward",
    statistics: {
      Overall: 90,
      Pace: 74,
      Shooting: 93,
      Passing: 83,
      Dribbling: 85,
      Defending: 45,
      Physical: 83,
    },
  },
  {
    id: 14,
    name: "Casemiro",
    club: "Manchester United",
    nationality: "Brazil",
    position: "Midfielder",
    statistics: {
      Overall: 89,
      Pace: 65,
      Shooting: 72,
      Passing: 77,
      Dribbling: 73,
      Defending: 87,
      Physical: 84,
    },
  },
  {
    id: 15,
    name: "Joshua Kimmich",
    club: "Bayern Munich",
    nationality: "Germany",
    position: "Midfielder",
    statistics: {
      Overall: 89,
      Pace: 70,
      Shooting: 76,
      Passing: 90,
      Dribbling: 84,
      Defending: 81,
      Physical: 76,
    },
  },
  {
    id: 16,
    name: "Jan Oblak",
    club: "Atlético Madrid",
    nationality: "Slovenia",
    position: "Goalkeeper",
    statistics: {
      Overall: 89,
      Pace: 52,
      Shooting: 20,
      Passing: 57,
      Dribbling: 44,
      Defending: 15,
      Physical: 77,
    },
  },
  {
    id: 17,
    name: "Vinícius Jr.",
    club: "Real Madrid",
    nationality: "Brazil",
    position: "Forward",
    statistics: {
      Overall: 88,
      Pace: 95,
      Shooting: 80,
      Passing: 78,
      Dribbling: 92,
      Defending: 30,
      Physical: 68,
    },
  },
  {
    id: 18,
    name: "Jude Bellingham",
    club: "Real Madrid",
    nationality: "England",
    position: "Midfielder",
    statistics: {
      Overall: 86,
      Pace: 78,
      Shooting: 80,
      Passing: 84,
      Dribbling: 86,
      Defending: 78,
      Physical: 82,
    },
  },
  {
    id: 19,
    name: "Pedri",
    club: "Barcelona",
    nationality: "Spain",
    position: "Midfielder",
    statistics: {
      Overall: 85,
      Pace: 77,
      Shooting: 73,
      Passing: 86,
      Dribbling: 89,
      Defending: 65,
      Physical: 68,
    },
  },
  {
    id: 20,
    name: "João Félix",
    club: "Barcelona",
    nationality: "Portugal",
    position: "Forward",
    statistics: {
      Overall: 84,
      Pace: 83,
      Shooting: 80,
      Passing: 79,
      Dribbling: 87,
      Defending: 38,
      Physical: 63,
    },
  }
]


export const findAllPlayers = async():Promise<PlayerModel[]> =>{
    return database
}

export const findPlayerById = async(id:number):Promise<PlayerModel | undefined> => {
    const player = database.find((player) => player.id === id)
    return player
}

export const insertPlayer = async(player: PlayerModel): Promise<void> => {
    database.push(player)
}